apiVersion: v1
kind: Service
metadata:
  name: carbon-footprint-service
spec:
  selector:
    app: carbon-footprint
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
